# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2741478ab6bacc1910527c067f479b384319e7d6da5f6921131dd05630af7d98faf4526e6b44ffd988ad65ce12619cbd5f787bbfc1fc76910e9e115a216acb1f

test:
  secret_key_base: 40e352ace2f3bd2d9839c2fd879286ebab289bece2c521fa2b3b3965c14e2c1f3af7c7471f955469cf43c3c9b092c938c97485173667f723dc91d3054dbe9c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
